# Exceptions


class ValidationError(Exception):
    pass
